basePath: /
definitions:
  main.Item:
    properties:
      description:
        type: string
      item_code:
        type: string
      price:
        type: integer
      quantity:
        type: integer
    type: object
  main.Order:
    properties:
      customer_name:
        type: string
      items:
        items:
          $ref: '#/definitions/main.Item'
        type: array
      order_at:
        type: string
      order_id:
        type: integer
    type: object
host: 127.0.0.1:8000
info:
  contact: {}
  description: this is description
  title: Orders API
  version: "0.1"
paths:
  /order:
    post:
      consumes:
      - application/json
      description: create Order include detail item
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Order'
            type: array
      summary: Create order
      tags:
      - root
swagger: "2.0"
